input {
  beats {
    port => 5044
  }
}

filter {
  mutate {
    add_field => {
      'learning_pipeline' => 'filebeat-to-logstash'
    }
  }
}

output {
  stdout {
    codec => rubydebug
  }

  elasticsearch {
    hosts => ['http://elasticsearch:9200']
    index => 'devops-learning-%{+YYYY.MM.dd}'
  }
}
